title: postcss-ant
email: cory@launchboxhq.com
baseurl: "/postcss-ant"
markdown: kramdown
exclude: ['node_modules', 'package.json', 'ant.js', 'README.md', 'Gemfile', 'css/in.scss', 'css/out.css', '*.sketch']
